### ISSUE TITLE
Select Characteristic to write to

### ISSUE THREAD

**Issue by kartik9k** [giomurru/ble-framework#6]
Hi, I wanted to use this asset in my application to be made in unity. Can I select which services/characteristic I want to write to?

If yes, then how?

If no, then please suggest some solutions?! 

TIA

**Comment by giomurru** [comment]
No. At the moment you can only read from the RX characteristic and write to the TX characteristic by using the static functions `public static byte[] GetData(int length)` and `public static void SendData(byte[] data)` defined in BleController.cs. 
For writing/reading another characteristic you should modify the native plugins.
