### ISSUE TITLE
bluetooth LE for android unity

### ISSUE THREAD

**Issue by projni** [giomurru/ble-framework#7]
Hello is this plugin works for Raspberry pi zero wirless?? i have to send and receive data between Raspberry and android using unity ! is this works for me?

**Comment by VinhBeo3101** [comment]
Hello. Did you send and receive data already?

**Comment by giomurru** [comment]
@projni This is a plugin for sending and receiving data from RedBearLab BLE Mini bluetooth module. I suppose you can use Raspberry but you have to do some modifications. The examples provided in the Unity project are based on an hardware setup using Arduino Mega 2560.
@VinhBeo3101 Yes, Android send/receive data has been fixed.

**Comment by projni** [comment]
Hi, Thanks for your response , I already changed the connection protocol , I already found another plugin but I couldn't use it because I found a problem with the Rpi BLE that I use exactly in the UART module, Thanks again !
